### ISSUE TITLE
<==Disconnect system.user.admin from ::ffff: fehlt ein Leerzeichen

### ISSUE THREAD

**Issue by RALFISBORN** [iobroker-community-adapters/ioBroker.logparser#145]
**Describe the bug**  
Standardmäßig ist in der Global Blacklist folgender Eintrag enthalten:
![image](https://github.com/iobroker-community-adapters/ioBroker.logparser/assets/47441243/a0910e8e-bb0a-4ee3-b05e-428d3a3ef146)

Es fehlt jedoch ein Leerzeichen zwischen <== und Disconnect.

Daher taucht trotzdem in den Logs die Fehlermeldung auf:
<== Disconnect system.user.admin from 

**To Reproduce**  
Es muss nur das Leerzeichen eingefügt werden:
![image](https://github.com/iobroker-community-adapters/ioBroker.logparser/assets/47441243/7c918d75-c20d-4ad3-9138-a497809259fe)

Dann taucht die Meldung nicht mehr auf.

**Expected behavior**  
Bitte das Leerzeichen einfügen. Dann wäre die Global Blacklist wieder korrekt.

**Versions:**  
- Fehler sowohl in die Stable Adapter Version als auch die V2.2.1

Vielen Dank

**Comment by ciddi89** [comment]
Danke für den Hinweis. Werde es anpassen 👍🏻
