### ISSUE TITLE
Replace date with "today" / "yesterday" and output in format #DD.MM.# hh:mm not working

### ISSUE THREAD

**Issue by BlackTigga** [iobroker-community-adapters/ioBroker.logparser#160]
Since few days the replacement of "today" / "yesterday" and the general output in format #DD.MM.# hh:mm is not working any more.

![Screnshot2](https://github.com/iobroker-community-adapters/ioBroker.logparser/assets/75884667/9a4d974f-95d0-4b06-b8ff-4f2daee560f9)

![Screnshot](https://github.com/iobroker-community-adapters/ioBroker.logparser/assets/75884667/7ea21f59-d255-43ca-a90c-f523c2ca19e5)

**Versions:**
Adapter version: 2.2.2
JS-Controller version: 5.0.19
Node version: 18.19.0
Operating system: linux

**Comment by ciddi89** [comment]
Wurde das System oder die Instanz mal neu gestartet? Wenn das noch bis vor ein paar Tagen ging, wurde irgend etwas geupdated oder so?

**Comment by BlackTigga** [comment]
Ja, tatsächlich hat ein Instanz Neustart geholfen.
