### ISSUE TITLE
Enhancement: automatically delete logs after x hours/days

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.logparser#19]
Original: https://github.com/Mic-M/ioBroker.logparser/issues/6

User request: https://forum.iobroker.net/post/402434

Kuddel: vllt könnte man ja einen Haken pro Filter setzen, dass das Log nach X Tagen oder so automatisch geleert wird. Oder z.B. jeden Tag um 0 Uhr
Negalein: nach X Tagen finde ich wäre sehr gut.
Need to further elaborate what makes sense. At this time I think it would make most sense to
have an option to remove logs older than x hours automatically.
Any more ideas/suggestions are welcome.

**Comment by Negalein** [comment]
nach X Tagen finde ich wäre sehr gut.

**Comment by ciddi89** [comment]
> nach X Tagen finde ich wäre sehr gut.

Allgemein oder für jeden rule einzeln einstellbar?

**Comment by Nashra-ioB** [comment]
Schließe mich da Negalein an, mir wäre auch lieber wenn es für jeden einstellbar ist.

**Comment by ciddi89** [comment]
Now available in latest v2.2.0
