### ISSUE TITLE
additional option removing partially script name

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.logparser#21]
Original: https://github.com/Mic-M/ioBroker.logparser/issues/19

Could you please add a second option to remove the script name partially. For example:

script.js.Material_Design_Widgets_Examples.AdapterStatus_2: should be only AdapterStatus_2:

**Comment by ciddi89** [comment]
Hello @Scrounger, 
I know the issue is over one year old yet. But we are trying to fix all issues now. Can you tell me please how du you mean that? If you activating `Remove script.js.Script_Name:` in the instance settings, it should look like your example? Or do you want a second option that only the part `script.js` will be removed and the script name should still be shown?

**Comment by Scrounger** [comment]
My wish is that last part will be visible.

`Remove script.js.Script_Name:` = false:
```
{
		"date": "Heute 09:13",
		"severity": "<span class='logWarn logSeverity'>warn</span>",
		"from": "javascript.0",
		"message": "script.js.VIS.Independent.Charts.Technik.Energie.pvForeCast: eine Warnung",
		"ts": 1677140019208
	}
```

`Remove script.js.Script_Name:` = true:
```
{
		"date": "Heute 09:13",
		"severity": "<span class='logWarn logSeverity'>warn</span>",
		"from": "javascript.0",
		"message": "eine Warnung",
		"ts": 1677140083042
	}
```

Example how i would like to have it, only `pvForeCast` should be visible:
```
{
		"date": "Heute 09:13",
		"severity": "<span class='logWarn logSeverity'>warn</span>",
		"from": "javascript.0",
		"message": "pvForeCast: eine Warnung",
		"ts": 1677140019208
	}
```

**Comment by ciddi89** [comment]
Aaah okay now I understand. Okay thanks for your example. I'll look what we can do about that.

**Comment by ciddi89** [comment]
@Scrounger 
Added option to remove only `script.js`. Will be available in next release. If u like to test it, install GitHub version, otherwise wait for release

**Comment by ciddi89** [comment]
Added in 2.1.0
