### ISSUE TITLE
alexa-history.js Fehler?

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.logparser#22]
Original: https://github.com/Mic-M/ioBroker.logparser/issues/34

Hallo,

ich habe immer einen Fehler im Log der scheinbar durch das Alexa Script kommt. Dieses lieft auch keine Infos mehr.

Details siehe original link

**Comment by mcm1957** [comment]
@ciddi89 
Do you have the possibility to analyze this?
I do not have Alexa - so I cannot process this problem easily.

**Comment by ciddi89** [comment]
Seems there is an issue in the script. But yes I can try to reproduce it and figuring out what's wrong.

**Comment by mcm1957** [comment]
Yes its not directly related to the adapter but provided by it. So if fixable, we should do it.

**Comment by ciddi89** [comment]
Fixed with v1.2.3
