### ISSUE TITLE
Missing CSS classes for date in tables

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.logparser#25]
Original: https://github.com/Mic-M/ioBroker.logparser/issues/39

Using Adapter v1.1.0

Configured tables are being created fine, but after a while the date cells loose their classes logWarn and logError.

But it's not clear, when this does happen. The following screenshot shows 2 tables. On top side a 2-row table and after that a full length table.

![image](https://user-images.githubusercontent.com/28575778/220422852-5e5b56d1-d03c-464f-8c58-ccab603ebc1a.png)

As you can see they are different. In the full length table the entries of today are colored.

To reproduce this manually just set another filter on logparser.0.visualization.table0.selection. Once it is selected the date cells have almost every time no classes.

**Comment by Standarduser** [comment]
Not fixed yet (v2.2.0)

<img width="805" alt="Bildschirmfoto 2023-08-13 um 13 12 41" src="https://github.com/iobroker-community-adapters/ioBroker.logparser/assets/8029204/b8e331d4-28cd-480b-9cbb-5f83ab9b3b11">

<img width="481" alt="Bildschirmfoto 2023-08-13 um 13 11 58" src="https://github.com/iobroker-community-adapters/ioBroker.logparser/assets/8029204/20b42e90-d9fc-4a30-b036-8e36be07138d">

**Comment by ciddi89** [comment]
with last commit it should be fix. I have to do some other bugfixes/corrections the next days, then I will create a release.
