### ISSUE TITLE
[QA] consider migrating to json config

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.logparser#36]
If possible - without loosing functionality - the config interface should be migrated to json based config.

**Comment by ciddi89** [comment]
I was also thinking about it and would change it to jsonData if you like

**Comment by ciddi89** [comment]
Okay I will make the whole program with translations and jsonConfig and will look what we can migrate so the user will have as less work as possible. 

I have open a new branch with my name so I/we can test the changes before I push it in the main branch.

**Comment by mcm1957** [comment]
Implemented at 2.0.0
