### ISSUE TITLE
visualization not working

### ISSUE THREAD

**Issue by Martin-int01** [iobroker-community-adapters/ioBroker.logparser#66]
Since the update from version 1.x to 2.1.1 the visualization is not working anymore. the log messages appears in the filter json. The visualization json remains empty. It works for 2-3 log entries, if I delete the whole visualization table. Then it stops working again.

edit:
I discovered, that if I reselect the selection in the visualization objects, all prior entries are appearing. I think this is a refresh problem.

**Versions:**  
 - Adapter version: 2.1.1
 - node.js: 16.19.1
 - NPM: 8.19.3
 - OS: Ubuntu 22.04

**Comment by ciddi89** [comment]
should be fixed with 2.1.2
